# Generated by Django 5.0.4 on 2024-05-01 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('director', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=700)),
                ('genre', models.CharField(choices=[('A', 'ACTION'), ('CO', 'COMEDY'), ('CR', 'CRIME'), ('D', 'DRAMA'), ('F', 'FANTASY'), ('H', 'HORROR'), ('M', 'MYSTERY'), ('O', 'OTHER'), ('R', 'ROMACTIC'), ('SF', 'SCI-FI'), ('T', 'THRILLER'), ('W', 'WAR'), ('WE', 'WESTERN')], max_length=3)),
                ('category', models.CharField(choices=[('TR', 'TOP RATED'), ('MW', 'MOST WATCHED'), ('RA', 'RECENTLY ADDED')], max_length=3)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateField()),
                ('poster', models.URLField(default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
            ],
        ),
    ]
